branches:
  except:
    - /dev.*/  # do not build dev branch

image:
  - Visual Studio 2017

platform:
  - x86

configuration:
  - Debug
  - Release

environment:
  VCPKG_ROOT: C:\tools\vcpkg

cache: c:\tools\vcpkg\installed\ -> scripts\deps.ps1  # cache the installed vcpkg packages

install:
  - git submodule update --init --recursive
  - powershell scripts\deps.ps1

build_script:
  - powershell scripts\generate.ps1 %CONFIGURATION%
  - powershell scripts\build.ps1 %CONFIGURATION%

test_script:
  - '%APPVEYOR_BUILD_FOLDER%/build/%CONFIGURATION%/dicebot.gtest.data_test.exe'
  - '%APPVEYOR_BUILD_FOLDER%/build/%CONFIGURATION%/dicebot.gtest.entry_test.exe'
  - '%APPVEYOR_BUILD_FOLDER%/build/%CONFIGURATION%/dicebot.gtest.number_test.exe'
  - '%APPVEYOR_BUILD_FOLDER%/build/%CONFIGURATION%/dicebot.gtest.roll_test.exe'
